[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E", "F", "I", "UP", "N"]
ignore = ["E501"]

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-q --maxfail=1"
testpaths = ["WORKING_FILES/tests"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
strict = false
